# Generated by Django 4.0.2 on 2022-02-07 12:08

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candle_color', models.PositiveIntegerField(choices=[(1, 'BLACK'), (2, 'WHITE'), (3, 'BLUE')])),
                ('candle_flavor', models.PositiveIntegerField(choices=[(1, 'Цитрусовые'), (2, 'Пряные'), (3, 'Хвойные'), (4, 'Фруктовые'), (5, 'Травяные')])),
                ('candle_volume', models.PositiveIntegerField(choices=[(1, 'small'), (2, 'middle'), (3, 'big')])),
                ('candle_wick', models.PositiveIntegerField(choices=[(1, 'Плоские фитили'), (2, 'Квадратные фитили'), (3, 'Армированные фитили')])),
                ('description', models.TextField(max_length=1000, null=True)),
                ('image', models.ImageField(upload_to='product/%Y/%m/%d')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('count', models.IntegerField(db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'Свеча',
                'verbose_name_plural': 'Свечи',
                'ordering': ('-count',),
            },
        ),
        migrations.CreateModel(
            name='UserCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=17)),
                ('address', models.CharField(max_length=255)),
                ('candle_color', models.PositiveIntegerField(choices=[(1, 'BLACK'), (2, 'WHITE'), (3, 'BLUE')])),
                ('candle_flavor', models.PositiveIntegerField(choices=[(1, 'Цитрусовые'), (2, 'Пряные'), (3, 'Хвойные'), (4, 'Фруктовые'), (5, 'Травяные')])),
                ('candle_volume', models.PositiveIntegerField(choices=[(1, 'small'), (2, 'middle'), (3, 'big')])),
                ('candle_wick', models.PositiveIntegerField(choices=[(1, 'Плоские фитили'), (2, 'Квадратные фитили'), (3, 'Армированные фитили')])),
                ('status', models.PositiveIntegerField(choices=[(1, 'In processing'), (2, 'sent')], db_index=True)),
                ('created_order', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ordering', to='candly.usercandle')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-status',),
            },
        ),
    ]
